document.writeln("<header class=\'header\'>");
document.writeln("    <nav class=\'navbar navbar-expand-lg py-lg-0\'>");
document.writeln("        <div class=\'container\'>");
document.writeln("            <button type=\'button\' data-toggle=\'collapse\' data-target=\'#navbarSupportedContent\' aria-controls=\'navbarSupportedContent\' aria-expanded=\'false\' aria-label=\'Toggle navigation\' class=\'navbar-toggler navbar-toggler-right small\'><span class=\'text-uppercase mr-2\'>Menu</span><i class=\'fas fa-bars\'></i></button>");
document.writeln("            <div id=\'navbarSupportedContent\' class=\'collapse navbar-collapse\'>");
document.writeln("                <ul class=\'navbar-nav ml-auto d-lg-flex align-items-lg-center\'>");
document.writeln("                    <li class=\'nav-item\'><a href=\'index.html\' class=\'nav-link font-weight-bold text-uppercase px-lg-3 py-lg-4\'>首页 </a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'nav-item\'><a href=\'business.html\' class=\'nav-link font-weight-bold text-uppercase px-lg-3 py-lg-4\'>财经 </a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'nav-item\'><a href=\'health.html\' class=\'nav-link font-weight-bold text-uppercase px-lg-3 py-lg-4 active\'>健康</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'nav-item\'><a href=\'health.html\' class=\'nav-link font-weight-bold text-uppercase px-lg-3 py-lg-4 \'>科技</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'nav-item\'><a href=\'health.html\' class=\'nav-link font-weight-bold text-uppercase px-lg-3 py-lg-4 \'>文化</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'nav-item\'><a href=\'health.html\' class=\'nav-link font-weight-bold text-uppercase px-lg-3 py-lg-4 \'>社会</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'nav-item\'><a href=\'health.html\' class=\'nav-link font-weight-bold text-uppercase px-lg-3 py-lg-4 \'>娱乐</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'nav-item\'><a href=\'else.html\' class=\'nav-link font-weight-bold text-uppercase px-lg-3 py-lg-4 \'>其他</a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </nav>");
document.writeln("</header>");